
######################### Global constants #########################

# These values should not be changed, except in test code.

SAMPLE_RATE = 44100

# Voice parameters

MAX_TREMOLO_RATE = 100
MAX_TREMOLO_DEPTH = 100
MAX_RING_MOD_RATE = 50
MAX_VIBRATO_RATE = 100
MAX_VIBRATO_DEPTH = 100
MAX_HARMONIC_BOOST = 100
MAX_UNISON_VOICES = 8
MAX_UNISON_DETUNE = 100
UNISON_SCALE_FACTOR = 0.20 # Used to adjust the detune percentage.

# ADSR shaper constants (times in milli-second units)

MAX_ATTACK = 100
MAX_DECAY = 100
MAX_SUSTAIN = 400
MAX_RELEASE = 100
MAX_ENVELOPE_TIME = MAX_ATTACK + MAX_DECAY + MAX_SUSTAIN + MAX_RELEASE

DEFAULT_ATTACK = 20
DEFAULT_DECAY = 20
DEFAULT_SUSTAIN = 100
DEFAULT_SUSTAIN_LEVEL = 50
DEFAULT_RELEASE = 20

NUM_OCTAVES = 3
LOWEST_TONE = 110
NUM_KEYS = (12 * NUM_OCTAVES) + 1

MAX_VOICES = 12
MAX_TIMESLOTS = 60

DEFAULT_FREQUENCY = 440

FREQUENCY = 220    # Hz
WIDTH = 50
MAX_DURATION = 1000
STEREO = False

ATTACK = 200
DECAY = 200
SUSTAIN_TIME = 500
SUSTAIN_LEVEL = 50
RELEASE = 100

# Optional features - should be True or False

HARMONIC_BOOST_ENABLED = True
VIBRATO_ENABLED = True
RING_MODULATION_ENABLED = True
UNISON_ENABLED = True
TREMOLO_ENABLED = True
